QuanLyHocSinhDuHoc/Models/Entities/QUYEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
    }
}

QuanLyHocSinhDuHoc/Controllers/QuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyHocSinhDuHoc.Models.Entities;
using PaymentSystem.Controllers;
using QuanLyHocSinhDuHoc.CommonXuLy;

namespace QuanLyHocSinhDuHoc.Controllers
{
    public class QuyenController : BaseController
    {
        dbXulyTThsEntities db = new dbXulyTThsEntities();
        // GET: List Quyền
        public ActionResult Index()
        {
            ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
            if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
            {
                return View(db.QUYENs.ToList());
            } return RedirectToAction("Index", "Home");
        }
        //GET: Thêm quyền
        public ActionResult Themmoi()
        {
             ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
             if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
             {
                 return View();
             } return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult Themmoi(QUYEN quyen)
        {    
             ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
             if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
             {
                 if (ModelState.IsValid)
                 {
                     db.QUYENs.Add(quyen);
                     db.SaveChanges();
                     return RedirectToAction("Index");
                 }
                 return View();
             } return RedirectToAction("Index", "Home");
        }
        //GET: Cập nhật quyền

        public ActionResult SuaQuyen(int id)
        {
             ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
             if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
             {
                 return View(db.QUYENs.Find(id));
             } return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult SuaQuyen(QUYEN quyen)
        {
             ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
             if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
             {
                 if (ModelState.IsValid)
                 {
                     QUYEN quyenUpdate = db.QUYENs.Find(quyen.Id);
                     quyenUpdate.Ten = quyen.Ten;
                     quyenUpdate.MoTa = quyen.MoTa;
                     db.Entry(quyenUpdate).State = System.Data.Entity.EntityState.Modified;
                     db.SaveChanges();
                     return RedirectToAction("Index");
                 }
                 return View();
             } return RedirectToAction("Index", "Home");
        }

        //GET: Xóa quyền
        [HttpPost]
        public JsonResult XoaQuyen(string id)
        {
            if (ModelState.IsValid)
            {
                QUYEN quyen = db.QUYENs.Find(Convert.ToInt32(id));
                db.QUYENs.Remove(quyen);
                db.SaveChanges();
                return Json("Yes", JsonRequestBehavior.AllowGet);
            }
            return Json("No", JsonRequestBehavior.AllowGet);
        }
    }
}

QuanLyHocSinhDuHoc/Views/Quyen/Index.cshtml
@model IEnumerable<QuanLyHocSinhDuHoc.Models.Entities.QUYEN>
@{
    ViewBag.Title = "Danh sách quyền hạn";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Danh sách quyền hạn</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a title="Thêm" data-toggle="tooltip" data-placement="bottom" class="dropdown-toggle" href="@Url.Content("/Quyen/Themmoi")"><i class="fa fa-plus"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">

                        <!-- Bảng dữ liệu -->
                        <div class="row">
                            <div class="col-sm-12">
                                <p id="ThongBaoIndex" style="color:red;font-weight:bold;"></p>
                                <table class="table table-striped table-bordered" style="overflow-x:auto;" id="TableListHs">
                                    <thead>
                                        <tr>
                                            <th><div class="word-wrap">STT</div></th>
                                            <th><div class="word-wrap">Tên quyền</div></th>
                                            <th><div class="word-wrap">Mô tả</div></th>                                          
                                            <th></th>
                                        </tr>
                                    </thead>

                                    <tbody id="listHS">
                                        @{
                                            if (Model != null)
                                            {
                                                //var i = ((int)Session["trangdangload"] - 1) * 10 + 1;
                                                var i = 1;
                                                foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td><div class="word-wrap">@i</div></td>
                                                        <td><div class="word-wrap">@item.Ten</div></td>
                                                        <td><div class="word-wrap">@item.MoTa</div></td>                                                      
                                                        
                                                        <td class="actions">
                                                            <a data-toggle="tooltip" data-placement="bottom" target="_blank" title="Sửa" href="@Url.Action("SuaQuyen", "Quyen", new { @id = @item.Id })">
                                                                <i class="fa fa-edit"></i>
                                                            </a>
                                                            <a id="deleteND" href="#" title="Xóa" onclick="Delete(@item.Id);return false;">
                                                                <i class="fa fa-close"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    i = @i + 1;
                                                }
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Bảng dữ liệu -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function Delete(id_quyen)
    {
        var yes =confirm('Bạn có thực sự muốn xóa không ???');
        if(yes ==true)
        {
            $.ajax({
                url: "/Quyen/XoaQuyen",
                type: "POST",
                dataType: "json",
                data: "{id:" + id_quyen + "}",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data == "Yes")
                        window.location.href = "/Quyen/Index";
                    else
                        alert("Xóa thất bại!");
                },
                error: function (er) {
                    alert(er);
                }

            });
        }
    }

</script>

QuanLyHocSinhDuHoc/Views/Quyen/SuaQuyen.cshtml
@model QuanLyHocSinhDuHoc.Models.Entities.QUYEN
@{
    ViewBag.Title = "Cập nhật quyền hạn";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}

<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Cập nhật quyền hạn</h2>
                    <div class="clearfix"></div>
                </div>
                @{
                    if (Model != null)
                    {
                        <div class="x_content">
                            <form class="form-horizontal form-label-left" method="post" id="formAddND">
                                <div class="row">
                                    <div class="col-md-10 col-sm-10 col-xs-10">
                                        <br /><br />
                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                Tên quyền <span class="required">*</span>
                                            </label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <input class="form-control col-md-7 col-xs-12" id="TenQuyen" name="Ten" required="required" value="@Model.Ten" type="text" />
                                            </div>
                                        </div>
                                        <p id="messThemQ" style="color:red;font-weight:bold;"></p>
                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                Mô tả
                                            </label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <textarea class="form-control col-md-7 col-xs-12" id="MoTa" name="MoTa" type="text">@Model.MoTa</textarea>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <div class="row">
                                    <div class="ln_solid"></div>
                                    @*chức năng*@
                                    <div class="form-group">
                                        <div class="col-md-6 col-md-offset-3">
                                            <button class="btn btn-success" id="Sublmit" type="submit" style="margin-left:30%;">Cập nhật</button>
                                            <a href="/Quyen/Index" class="btn btn-primary">Huỷ</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    }

                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#Sublmit").click(function () {
        if ($("#TenQuyen").val == "") {
            $("#messThemQ").text("Tên quyền không được để trống!");
            return false;
        }
        else $("#messThemQ").text("");

    });
</script>

QuanLyHocSinhDuHoc/Views/Quyen/Themmoi.cshtml
@{
    ViewBag.Title = "Thêm mới quyền hạn";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Thêm mới quyền hạn</h2>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <form class="form-horizontal form-label-left" method="post" id="formAddND">
                        <div class="row">
                            <div class="col-md-10 col-sm-10 col-xs-10">
                                <br /><br />
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Tên quyền <span class="required">*</span>
                                    </label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="TenQuyen" name="Ten" required="required" placeholder="Tên quyền hạn" type="text" />
                                    </div>
                                </div>
                                <p id="messThemQ" style="color:red;font-weight:bold;"></p>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Mô tả
                                    </label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <textarea class="form-control col-md-7 col-xs-12" id="MoTa" name="MoTa" type="text"></textarea>
                                    </div>
                                </div>
                               
                            </div>
                        </div>

                        <div class="row">
                            <div class="ln_solid"></div>
                            @*chức năng*@
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button class="btn btn-success" id="Sublmit" type="submit" style="margin-left:30%;">Thêm mới</button>
                                    <a href="/Quyen/Index" class="btn btn-primary">Huỷ</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#Sublmit").click(function () {
        if ($("#TenQuyen").val == "") {
            $("#messThemQ").text("Tên quyền không được để trống!");
            return false;
        }
        else $("#messThemQ").text("");

    });
</script>