QuanLyHocSinhDuHoc/Models/Entities/GIAYCHUNGTHUC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAYCHUNGTHUC
    {
        public int id { get; set; }
        public string TenGiay { get; set; }
        public string Anh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> id_HSHS { get; set; }
    }
}

QuanLyHocSinhDuHoc/Controllers/GiayChungThucController.cs
using QuanLyHocSinhDuHoc.CommonXuLy;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyHocSinhDuHoc.Models.Entities;

namespace QuanLyHocSinhDuHoc.Controllers
{
    public class GiayChungThucController : Controller
    {
        dbXulyTThsEntities db = new dbXulyTThsEntities();

        // GET: GiayChungThuc
        public ActionResult Themmoi(int? id_hs)
        {
            ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
            if (quyenNguoiDung != null && (quyenNguoiDung.Quyen.Ten == "QuanLyThongTinHocSinh" || quyenNguoiDung.Quyen.Ten == "Admin"))
            {
                Session["file"] = null;
                Session["id_hsDetail"] = null;

                return View();
            }
            return RedirectToAction("Index", "Home");
        }
        //upload File
        [HttpPost]
        public JsonResult SaveGCT()
        {
            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var file = Request.Files["HelpSectionFile"];
                //lưu tên file
                var fileName = Path.GetFileName(file.FileName);
                //lưu đường dẫn
                var path = Path.Combine(Server.MapPath("~/Content/filePDF"), fileName);
                // file is uploaded
                var type = file.ContentType;
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Thongbao = "File đã tồn tại";
                }
                else
                {
                    if (type == "application/docx" || type == "application/pdf")
                        file.SaveAs(path);
                }
                Session["file"] = fileName;
                int id_HS = (int)Session["id_HS"];
                if(id_HS!=null)
                {
                    GIAYCHUNGTHUC giay = new GIAYCHUNGTHUC();
                    giay.Anh = fileName;
                    giay.TenGiay = fileName;
                    giay.id_HSHS = id_HS;
                    db.GIAYCHUNGTHUCs.Add(giay);
                    db.SaveChanges();
                }

                return Json(fileName, JsonRequestBehavior.AllowGet);
            }
            Session["file"] = null;
            return Json("Khong", JsonRequestBehavior.AllowGet);
        }

        public ActionResult DetailGCT()
        {
            ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
            if (quyenNguoiDung != null && (quyenNguoiDung.Quyen.Ten == "QuanLyThongTinHocSinh" || quyenNguoiDung.Quyen.Ten == "Admin"))
            {
                int id_hs = (int)Session["id_hsDetail"];
                HOCSINH hocsinh = db.HOCSINHs.Find(id_hs);
                List<GIAYCHUNGTHUC> listGiay = db.GIAYCHUNGTHUCs.Where(n => n.id_HSHS == hocsinh.id).ToList();
                if (listGiay.Count > 0)
                {
                    ViewBag.ThongbaoBTN = "OK";
                    return View(listGiay);
                }
                ViewBag.ThongbaoBTN = "NO";
                return View();

            } return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public JsonResult CapNhatGCT()
        {
            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var file = Request.Files["HelpSectionFile"];
                //lưu tên file
                var fileName = Path.GetFileName(file.FileName);
                //lưu đường dẫn
                var path = Path.Combine(Server.MapPath("~/Content/filePDF"), fileName);
                // file is uploaded
                var type = file.ContentType;
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Thongbao = "File đã tồn tại";
                }
                else
                {
                    if (type == "application/docx" || type == "application/pdf")
                        file.SaveAs(path);
                }
                Session["file"] = fileName;
                int id_HS = (int)Session["id_hsDetail"];
                if (id_HS != null)
                {
                    GIAYCHUNGTHUC giay = new GIAYCHUNGTHUC();
                    giay.Anh = fileName;
                    giay.TenGiay = fileName;
                    giay.id_HSHS = id_HS;
                    db.GIAYCHUNGTHUCs.Add(giay);
                    db.SaveChanges();
                }

                return Json(fileName, JsonRequestBehavior.AllowGet);
            }
            Session["file"] = null;
            return Json("Khong", JsonRequestBehavior.AllowGet);
        }
        public ActionResult Load()
        {
            int id_hs = (int)Session["id_hsDetail"];
            Session["chuyenTab"] = 8;
            return RedirectToAction("DetailChung", "HocSinh", new { id = id_hs });
        }
        public ActionResult Xoa(int id)
        {
            GIAYCHUNGTHUC gcthuc = db.GIAYCHUNGTHUCs.Find(id);
            if(gcthuc!=null)
            {
                db.GIAYCHUNGTHUCs.Remove(gcthuc);
                db.SaveChanges();
                int id_hs = (int)Session["id_hsDetail"];
                Session["chuyenTab"] = 8;
                return RedirectToAction("DetailChung", "HocSinh", new { id = id_hs });
            }
            return View();
        }
    }
}

QuanLyHocSinhDuHoc/Views/GiayChungThuc/DetailGCT.cshtml
@model IEnumerable<QuanLyHocSinhDuHoc.Models.Entities.GIAYCHUNGTHUC>
@{
    //var id_hs = Request["id"];
    // var id_hs = Request.Url.Segments.Last();
    var id_hs = (int)Session["id_hsDetail"];
    if (ViewBag.ThongbaoBTN == "NO")
    {
        <h2 style='color:#0070e2;'><strong>Chưa cập nhật giấy chứng thực</strong></h2>
        <button type="button" onclick="$('#fileGCT').click()" class="btn btn-sm btn-primary" style="width:230px;">Chọn file<br /><i>(Chú ý file dạng Pdf!)</i></button>
        <input type="file" id="fileGCT" name="fileGCT" style="display: none;" class="form-control">
        <a class="btn btn-sm btn-primary" href="@Url.Action("Load","GiayChungThuc")">Load</a>
    }
    if (ViewBag.ThongbaoBTN == "OK")
    {
        <button type="button" onclick="$('#fileGCT').click()" class="btn btn-sm btn-primary" style="width:230px;">Thêm file<br /><i>(Chú ý file dạng Pdf!)</i></button>
        <input type="file" id="fileGCT" name="fileGCT" style="display: none;" class="form-control">
        <a class="btn btn-sm btn-primary" href="@Url.Action("Load","GiayChungThuc")">Load</a><br />
        var k = 1;
        foreach (var item in Model)
        {
            <a class="btn btn-success" onclick ="ClickXoaFile(@item.id)" >Xóa</a>
            <a class="btn btn-success" href="@Url.Action("TestPdf", "XuLyHocSinh", new { @url  =@item.Anh})" target="@item.id" onclick="clickHienGCT(@item.id)">Hiện thị file @k</a>
            <iframe allowfullscreen frameborder="1" height="400px" width="100%" name="@item.id" hidden id="@item.id"></iframe>
         
            k++;
        }
    }
}
<script type="text/javascript">
    function ClickXoaFile(id)
    {
        var conF =confirm("Bạn có thực sự muốn xóa không?");
        if(conF==true)
            window.location.href ="/GiayChungThuc/Xoa/"+id;
        else return false;
    }
    function clickHienGCT(id){
        $("#"+id).show();
    };
    $(document).ready(function () {
        $("#fileGCT").change(function () {
            debugger;
            var data = new FormData();
            var files = $("#fileGCT").get(0).files;
            if (files.length > 0) {
                data.append("HelpSectionFile", files[0]);
            }
            $.ajax({
                url: "/GiayChungThuc/CapNhatGCT",
                type: "POST",
                processData: false,
                contentType: false,
                data: data,
                success: function (data) {
                    if (data != "Khong")
                        alert("Lưu trữ thành công!!!");
                },
                error: function (er) {
                    alert(er);
                }

            });
        });
    });
</script>

QuanLyHocSinhDuHoc/Views/GiayChungThuc/Themmoi.cshtml
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Lưu trữ thông tin giấy chứng thực</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class=" item form-group">
                    <button type="button" onclick="$('#fileGCT').click()" class="btn btn-sm btn-primary" style="width:230px;">Chọn file<br /><i>(Chú ý file dạng Pdf!)</i></button>
                    <input type="file" id="fileGCT" name="fileGCT" style="display: none;" class="form-control">
                </div>
            </div>
        </div>
</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#fileGCT").change(function () {
            debugger;
            var data = new FormData();
            var files = $("#fileGCT").get(0).files;
            if (files.length > 0) {
                data.append("HelpSectionFile", files[0]);
            }
            $.ajax({
                url: "/GiayChungThuc/SaveGCT",
                type: "POST",
                processData: false,
                contentType: false,
                data: data,
                success: function (data) {
                    if (data != "Khong")
                        alert("Lưu trữ thành công!!!");
                },
                error: function (er) {
                    alert(er);
                }

            });
        });
    });
</script>