QuanLyHocSinhDuHoc/Models/Entities/PHANQUYEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhDuHoc.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public int id_quyen { get; set; }
        public int id_truycap { get; set; }
        public string MoTa { get; set; }
    }
}

QuanLyHocSinhDuHoc/Controllers/PhanQuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyHocSinhDuHoc.Models.Entities;
using PaymentSystem.Controllers;
using QuanLyHocSinhDuHoc.CommonXuLy;

namespace QuanLyHocSinhDuHoc.Controllers
{
    public class PhanQuyenController : BaseController
    {
        dbXulyTThsEntities db = new dbXulyTThsEntities();
        // GET: PhanQuyen
        public ActionResult Index()
        {
            ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
            if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
            {
                return View(db.PHANQUYENs.ToList());

            } return RedirectToAction("Index", "Home");
        }
        //GET: Thêm 
        public ActionResult Themmoi()
        {
            ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
            if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
            {
                ViewBag.Quyen = db.QUYENs.ToList();
                ViewBag.QuyenTC = db.QUYENTRUYCAPs.ToList();
                return View();
            } return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult Themmoi(PHANQUYEN Pquyen)
        {
            ModelQuyenNguoiDung quyenNguoiDung = Session["QuyenNguoiDung"] as ModelQuyenNguoiDung;
            if (quyenNguoiDung != null && quyenNguoiDung.Quyen.Ten == "Admin")
            {
                if (ModelState.IsValid)
                {
                    db.PHANQUYENs.Add(Pquyen);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            } return RedirectToAction("Index", "Home");
        }
        //GET: Check kiểm tra trùng
        [HttpPost]
        public JsonResult CheckPhanQuyen(string id_quyen, string id_truycap)
        {
             PHANQUYEN phanquyen = db.PHANQUYENs.Find(Convert.ToInt32(id_quyen), Convert.ToInt32(id_truycap));                
             if(phanquyen==null)
                return Json("No", JsonRequestBehavior.AllowGet);
             else return Json("Yes", JsonRequestBehavior.AllowGet);
        }
        //GET: Xóa
        [HttpPost]
        public JsonResult XoaPhanQuyen(string id_quyen, string id_quyenTC)
        {
            if (ModelState.IsValid)
            {
                PHANQUYEN phanquyen = db.PHANQUYENs.Find(Convert.ToInt32(id_quyen), Convert.ToInt32(id_quyenTC));
                db.PHANQUYENs.Remove(phanquyen);
                db.SaveChanges();
                return Json("Yes", JsonRequestBehavior.AllowGet);
            }
            return Json("No", JsonRequestBehavior.AllowGet);
        }



        ////GET: Cập nhật
        //public ActionResult SuaPhanQuyen(int id_quyen, int id_truycap)
        //{
        //    ViewBag.Quyen = db.QUYENs.ToList();
        //    ViewBag.QuyenTC = db.QUYENTRUYCAPs.ToList();
        //    return View(db.PHANQUYENs.Find(id_quyen, id_truycap));
        //}
        //[HttpPost]
        //public ActionResult SuaPhanQuyen(PHANQUYEN phanquyen)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        int id_quyen = Convert.ToInt32(Request["id_quyen"]);
        //        int id_truycap = Convert.ToInt32(Request["id_truycap"]);
        //        PHANQUYEN phanquyenOld = db.PHANQUYENs.Find(id_quyen, id_truycap);
        //        PHANQUYEN phanquyenUpdate = db.PHANQUYENs.Find(phanquyen.id_quyen, phanquyen.id_truycap);
        //        if (phanquyenUpdate == null)
        //        {
        //            phanquyenUpdate.id_quyen = phanquyen.id_quyen;
        //            phanquyenUpdate.id_truycap = phanquyen.id_truycap;
        //            phanquyenUpdate.MoTa = phanquyen.MoTa;
        //            db.Entry(phanquyenUpdate).State = System.Data.Entity.EntityState.Modified;
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        return View();
        //    }
        //    return View();
        //}

    }
}

QuanLyHocSinhDuHoc/Views/PhanQuyen/Index.cshtml
@model IEnumerable<QuanLyHocSinhDuHoc.Models.Entities.PHANQUYEN>
@using QuanLyHocSinhDuHoc.Models.Entities

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Danh sách phân quyền</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a title="Thêm" data-toggle="tooltip" data-placement="bottom" class="dropdown-toggle" href="@Url.Content("/PhanQuyen/Themmoi")"><i class="fa fa-plus"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">

                        <!-- Bảng dữ liệu -->
                        <div class="row">
                            <div class="col-sm-12">
                                <p id="ThongBaoIndex" style="color:red;font-weight:bold;"></p>
                                <table class="table table-striped table-bordered" style="overflow-x:auto;" id="TableListHs">
                                    <thead>
                                        <tr>
                                            <th><div class="word-wrap">STT</div></th>
                                            <th><div class="word-wrap"> Quyền hạn</div></th>
                                            <th><div class="word-wrap">Link truy cập</div></th>
                                            <th><div class="word-wrap">Mô tả</div></th>
                                            <th></th>
                                        </tr>
                                    </thead>

                                    <tbody id="listHS">
                                        @{
                                            if (Model != null)
                                            {
                                                dbXulyTThsEntities db = new dbXulyTThsEntities();                                                                                                    
                                                var i = 1;
                                                foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td><div class="word-wrap">@i</div></td>
                                                        @{
                                                            QUYEN quyen = db.QUYENs.Find(item.id_quyen);
                                                            QUYENTRUYCAP quyenTC = db.QUYENTRUYCAPs.Find(item.id_truycap);
                                                        }
                                                        <td><div class="word-wrap">@quyen.Ten</div></td>
                                                        <td><div class="word-wrap">@quyenTC.LinkTruy_Cap</div></td>
                                                        <td><div class="word-wrap">@item.MoTa</div></td>
                                                        <td class="actions">
                                                            @*<a data-toggle="tooltip" data-placement="bottom" target="_blank" title="Sửa" href="@Url.Action("SuaPhanQuyen", "PhanQuyen", new { @id_quyen = @item.id_quyen, @id_truycap = @item.id_truycap })">
                                                                <i class="fa fa-edit"></i>
                                                            </a>*@
                                                            <a id="deleteND" href="#" title="Xóa" onclick="Delete(@item.id_quyen,@item.id_truycap);return false;">
                                                                <i class="fa fa-close"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    i = @i + 1;
                                                }
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Bảng dữ liệu -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function Delete(id_quyen,id_quyenTC)
    {
        var yes =confirm('Bạn có thực sự muốn xóa không ???');
        if(yes ==true)
        {
            $.ajax({
                url: "/PhanQuyen/XoaPhanQuyen",
                type: "POST",
                dataType: "json",
                data: "{id_quyen:" + id_quyen + ",id_quyenTC:"+id_quyenTC+"}",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data == "Yes")
                        window.location.href = "/PhanQuyen/Index";
                    else
                        alert("Xóa thất bại!");
                },
                error: function (er) {
                    alert(er);
                }

            });
        }
    }

</script>

QuanLyHocSinhDuHoc/Views/PhanQuyen/SuaPhanQuyen.cshtml
@model QuanLyHocSinhDuHoc.Models.Entities.PHANQUYEN
@using QuanLyHocSinhDuHoc.Models.Entities

@{
    ViewBag.Title = "Cập nhật phân quyền";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Phân quyền</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" method="post" id="formAddND">
                        @{
                            if (Model != null)
                            {
                                dbXulyTThsEntities db = new dbXulyTThsEntities();

                                QUYEN quyen = db.QUYENs.Find(@Model.id_quyen);
                                QUYENTRUYCAP quyenTC = db.QUYENTRUYCAPs.Find(@Model.id_truycap);
                                <div class="row">
                                    <div class="col-md-10 col-sm-10 col-xs-10">
                                        <br /><br />
                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                Quyền hạn <span class="required">*</span>
                                            </label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <select id="id_quyen" name="id_quyen" class="form-control col-md-7 col-xs-12">


                                                    <option value="@Model.id_quyen">@quyen.Ten</option>
                                                  @{
                                                        if (ViewBag.Quyen != null)
                                                        {
                                                            foreach (var item in ViewBag.Quyen)
                                                            {
                                                                if (@item.Id != @Model.id_quyen)
                                                                {
                                                                    <option value=@item.Id>@item.Ten</option>
                                                                }

                                                            }
                                                        }
                                                    }

                                                </select>
                                            </div>
                                        </div>
                                        <p id="messThemPQQ" style="color:red;font-weight:bold;"></p>
                                        <div class="item form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                Link truy cập
                                            </label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <select id="id_truycap" name="id_truycap" class="form-control col-md-7 col-xs-12">
                                                    <option value="@Model.id_truycap">@quyenTC.LinkTruy_Cap</option>
                                                    @{
                                                            if (ViewBag.QuyenTC != null)
                                                            {
                                                                foreach (var item in ViewBag.QuyenTC)
                                                                {
                                                                    if (@item.id != @Model.id_truycap)
                                                                    {
                                                                        <option value=@item.id>@item.LinkTruy_Cap</option>
                                                                    }
                                                                }
                                                            }
                                                    }

                                                </select>
                                            </div>
                                        </div>
                                        <p id="messThemPQTC" style="color:red;font-weight:bold;"></p>
                                    </div>
                                </div>
                           }
                        }                       
                        <div class="row">
                            <div class="ln_solid"></div>
                            @*chức năng*@
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button class="btn btn-success" id="Sublmit" type="submit" style="margin-left:30%;">Thêm mới</button>
                                    <a href="/PhanQuyen/Index" class="btn btn-primary">Huỷ</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#Sublmit").click(function () {
        var id_quyen =$("#id_quyen").val();
        var id_truycap =$("#id_truycap").val();
        if (id_quyen == "") {
            $("#messThemPQQ").text("Quyền không được để trống!");
            return false;
        }
        if (id_truycap == "") {
            $("#messThemPQTC").text("Quyền truy cập không được để trống!");
            return false;
        }
        $("#messThemQTC").text("");
        $("#messThemQTCLink").text("");
        $.ajax({
            url: "/PhanQuyen/CheckPhanQuyen",
            type: "POST",
            dataType: "json",
            data: "{id_quyen:" + id_quyen + ",id_truycap:" + id_truycap + "}",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                if (data == "Yes") {                
                    $("#messThemQTCLink").text("Đã tồn tại !!!");
                    return false;
                }
            },
            error: function (er) {
                alert(er);
            }

        });


    });
</script>

QuanLyHocSinhDuHoc/Views/PhanQuyen/Themmoi.cshtml
@{
    ViewBag.Title = "Phân quyền";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Phân quyền</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" method="post" id="formAddND">
                        <div class="row">
                            <div class="col-md-10 col-sm-10 col-xs-10">
                                <br /><br />
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Quyền hạn <span class="required">*</span>
                                    </label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <select id="id_quyen" name="id_quyen" class="form-control col-md-7 col-xs-12">
                                            <option value="">Chọn quyền hạn</option>
                                            @{
                                                if (ViewBag.Quyen != null)
                                                {
                                                    foreach (var item in ViewBag.Quyen)
                                                    {
                                                        <option value=@item.Id>@item.Ten</option>
                                                    }
                                                }
                                            }

                                        </select>                         
                                  </div>
                                </div>
                                <p id="messThemPQQ" style="color:red;font-weight:bold;"></p>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Link truy cập
                                    </label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <select id="id_truycap" name="id_truycap" class="form-control col-md-7 col-xs-12">
                                            <option value="">Chọn quyền truy cập</option>
                                            @{
                                                if (ViewBag.QuyenTC != null)
                                                {
                                                    foreach (var item in ViewBag.QuyenTC)
                                                    {
                                                        <option value=@item.id>@item.LinkTruy_Cap</option>
                                                    }
                                                }
                                            }

                                        </select>   
                                          </div>
                                </div>
                                <p id="messThemQTCLink" style="color:red;font-weight:bold;"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-10">
                                <p id="messTb" style="color:red;font-weight:bold;"></p>
                            </div>
                            <div class="col-md-7 col-sm-7 col-xs-10">
                                <p id="messTb" style="color:red;font-weight:bold;"></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="ln_solid"></div>
                            @*chức năng*@
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button class="btn btn-success" id="Sublmit" type="submit" style="margin-left:30%;">Thêm mới</button>
                                    <a href="/PhanQuyen/Index" class="btn btn-primary">Huỷ</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#id_quyen').blur(function(){
        var id_quyen =$("#id_quyen").val();
        var id_truycap =$("#id_truycap").val();
        if(id_quyen!="" & id_truycap!="")
        {
            $.ajax({
                url: "/PhanQuyen/CheckPhanQuyen",
                type: "POST",
                dataType: "json",
                data: "{id_quyen:" + id_quyen + ",id_truycap:" + id_truycap + "}",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data == "Yes") {                
                        $("#messTb").text("Đã tồn tại !!!");
                        $("#id_quyen").val("");
                        $("#id_truycap").val("");
                    } else {
                        $("#messTb").text("");
                    }
                },
                error: function (er) {
                    alert(er);
                }
            });
        }

    });
    $('#id_truycap').blur(function () {

        var id_quyen = $("#id_quyen").val();
        var id_truycap = $("#id_truycap").val();
        if (id_quyen != "" & id_truycap != "") {
            $.ajax({
                url: "/PhanQuyen/CheckPhanQuyen",
                type: "POST",
                dataType: "json",
                data: "{id_quyen:" + id_quyen + ",id_truycap:" + id_truycap + "}",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data == "Yes") {
                        $("#messTb").text("Đã tồn tại !!!");
                        $("#id_quyen").val("");
                        $("#id_truycap").val("");

                        
                    } else {
                        $("#messTb").text("");
                    }
                },
                error: function (er) {
                    alert(er);
                }

            });
        }

    });
    $('#id_quyen').focus(function () {
        $("#messTb").text("");
        $("#messThemQTC").text("");
        $("#messThemQTCLink").text("");
    });
    $('#id_quyen').focus(function () {
        $("#messTb").text("");
        $("#messThemQTC").text("");
        $("#messThemQTCLink").text("");
    });
    $("#Sublmit").click(function () {
        var id_quyen =$("#id_quyen").val();
        var id_truycap =$("#id_truycap").val();
        if (id_quyen == "") {
            $("#messThemPQQ").text("Quyền không được để trống!");
            return false;
        }
        if (id_truycap == "") {
            $("#messThemPQTC").text("Quyền truy cập không được để trống!");
            return false;
        }
        $("#messThemQTC").text("");
        $("#messThemQTCLink").text("");
    });
</script>