QuanLyHocSinhDuHoc/Controllers/SoHoKhauController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyHocSinhDuHoc.Models.Entities;
using PaymentSystem.Controllers;
using System.IO;

namespace QuanLyHocSinhDuHoc.Controllers
{
    public class SoHoKhauController : BaseController
    {
        dbXulyTThsEntities db = new dbXulyTThsEntities();
        // GET: SoHoKhau
        public ActionResult DetailSHK()
        {
            int id_hs = (int)Session["id_hsDetail"];
            List<HoKhau> listSHK = db.HoKhaus.Where(n => n.id_hs == id_hs).ToList();
            ViewBag.fileSHK = null;
            if(listSHK.Count>0)
            {
                foreach(var item in listSHK)
                {
                    if(item.fileSHK!=null && item.fileSHK!="")
                    {
                        ViewBag.fileSHK = item.fileSHK;
                        break;
                    }
                }
            }
            return View(listSHK);
        }
        //upload File
        [HttpPost]
        public JsonResult UpLoadFile()
        {
            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var file = Request.Files["HelpSectionFile"];
                //lưu tên file
                var fileName = Path.GetFileName(file.FileName);
                //lưu đường dẫn
                var path = Path.Combine(Server.MapPath("~/Content/filePDF"), fileName);
                // file is uploaded
                var type = file.ContentType;
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Thongbao = "File đã tồn tại";
                }
                else
                {
                    if (type == "application/pdf")
                    {
                        file.SaveAs(path);
                    }
                }
                if (type == "application/pdf")
                {
                   // Session["file"] = fileName;
                    int id_hs = (int)Session["id_hsDetail"];
                    List<HoKhau> listSHK = db.HoKhaus.Where(n => n.id_hs == id_hs).ToList();
                    foreach(var item in listSHK)
                    {
                        item.fileSHK = fileName;
                        db.Entry(item).State = System.Data.Entity.EntityState.Modified;
                        Session["chuyenTab"] = 7;
                        db.SaveChanges();

                    }
                    return Json(id_hs, JsonRequestBehavior.AllowGet);
                }
            }
            //Session["file"] = null;
            return Json("NO", JsonRequestBehavior.AllowGet);
        }
        #region //GET:Thêm mới
        public ActionResult Themmoi(int id_hs)
        {
            Session["file"] = null;
            Session["id_hsSHK"] = id_hs;
            Session["chuyenTab"] = 7;
            return View();
        }
        [HttpPost]
        public ActionResult Themmoi(HoKhau sohokhau)
        {
            if (ModelState.IsValid)
            {
                if (Session["file"]!=null)
                    sohokhau.fileSHK = (string)Session["file"];                    
                sohokhau.id_hs = (int)Session["id_hsSHK"];
                db.HoKhaus.Add(sohokhau);
                db.SaveChanges();
                Session["chuyenTab"] = 7;
                return RedirectToAction("DetailChung/" + sohokhau.id_hs, "HocSinh");                
            }
            return View();
        }
        #endregion

        #region //GET:Cập nhật-sửa
        public ActionResult Sua(int id_SHK)
        {
            Session["chuyenTab"] = 7;
            HoKhau hokhau = db.HoKhaus.Find(id_SHK);
            return View(hokhau);
        }
        [HttpPost]
        public ActionResult Sua(HoKhau sohokhau)
        {
            if(ModelState.IsValid)
            {
                db.Entry(sohokhau).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                Session["chuyenTab"] = 7;
                return RedirectToAction("DetailChung/" + sohokhau.id_hs, "HocSinh");
            }
            return View();
            
        }
        #endregion



    }
}

QuanLyHocSinhDuHoc/Views/SoHoKhau/DetailSHK.cshtml
@model IEnumerable<QuanLyHocSinhDuHoc.Models.Entities.HoKhau>
@{
    var id_hs = (int)Session["id_hsDetail"];
    if (@Model == null || Model.Count() == 0)
    {      
         <h2 style='color:#0070e2;'><strong>Chưa cập nhật số hộ khẩu</strong></h2>
         <a href="@Url.Action("Themmoi", "SoHoKhau", new { @id_hs = id_hs })" class="btn btn-primary">Thêm mới số hộ khẩu</a>
    }
    else
    {
        <h2 style='color:#0070e2;'><strong>Cập nhật thêm thông tin số hộ khẩu</strong></h2>
        <a href="@Url.Action("Themmoi", "SoHoKhau", new { @id_hs = id_hs })" class="btn btn-primary">Thêm mới</a>
        if (@ViewBag.fileSHK != null)
        {
            <a class="btn btn-success" href="@Url.Action("TestPdf", "XuLyHocSinh", new { @url = @ViewBag.fileSHK })" target="iframe_SHK" id="clickHienSHK">Hiện thị file</a>
            <iframe allowfullscreen height="400px" width="100%" name="iframe_SHK" hidden id="hienSHK"></iframe>

        }
        else
        {
            <div class=" item form-group">
                <button type="button" onclick="$('#fileSHK').click()" class="btn btn-sm btn-primary" style="width:230px;">Chọn file<br /><i>(Chú ý file dạng Pdf!)</i></button>
                <input type="file" id="fileSHK" name="fileSHK" style="display: none;" class="form-control">
            </div>
        }
        foreach (var item in Model)
        {
            <div class="">
                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>Thông tin @item.HoTen - quan hệ @item.QuanHe</h2>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <form class="form-horizontal form-label-left" method="post">
                                    <div class="row">
                                        <div class="col-md-10 col-sm-10 col-xs-10">
                                            <br /><br />
                                            <div hidden="hidden">
                                                <input class="form-control col-md-7 col-xs-12" id="id_hokhau" name="id_hokhau" value="@item.id_hokhau" type="text" />
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                    Họ tên <span class="required">*</span>
                                                </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input class="form-control col-md-7 col-xs-12"  name="HoTen" required="required" value="@item.HoTen" type="text" />
                                                </div>
                                                <div class="col-md-3 col-sm-3 col-xs-12">
                                                    @*<button class="btn btn-success" type="button" style="margin-left:30%;" onclick="CapNhat(@item.id_hokhau)">Cập nhật</button>*@
                                                    <a class="btn btn-success" href="@Url.Action("Sua", "SoHoKhau", new {id_SHK =@item.id_hokhau})" style="margin-left:30%;">Cập nhật</a>
                                                 </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                    Quốc tịch
                                                </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input class="form-control col-md-7 col-xs-12"  name="QuocTich" type="text" value="@item.QuocTich" />

                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                    Tuổi
                                                </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input class="form-control col-md-7 col-xs-12" name="Tuoi" value="@item.Tuoi" type="number" />
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                    Địa chỉ
                                                </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input class="form-control col-md-7 col-xs-12" name="DiaChi" value="@item.DiaChi" type="text" />
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                    Nghề nghiệp
                                                </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input class="form-control col-md-7 col-xs-12"  name="NgheNghiep" value="@item.NgheNghiep" type="text" />
                                                </div>
                                            </div>
                                            <div class="item form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                                    Quan hệ
                                                </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input class="form-control col-md-7 col-xs-12" name="QuanHe" value="@item.QuanHe" type="text" />
                                                </div>
                                            </div>
                                            <p id="messThemHS" style="color:red;font-weight:bold;"></p>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
}

<script type="text/javascript">
    $("#clickHienSHK").click(function () {
        $("#hienSHK").show();
    });
    $(document).ready(function () {
        $("#fileSHK").change(function () {
            debugger;
            var data = new FormData();
            var files = $("#fileSHK").get(0).files;
            if (files.length > 0) {
                data.append("HelpSectionFile", files[0]);
            }
            $.ajax({
                url: "/SoHoKhau/UpLoadFile",
                type: "POST",
                processData: false,
                contentType: false,
                data: data,
                success: function (data) {
                    if (data == "NO")
                        alert("Lỗi loại file lưu trữ");
                    else {

                        window.location.href = "?id=" + data;
                    }
                },
                error: function (er) {
                    alert(er);
                }

            });
        });
    });
    //function CapNhat(id_hokhau)
    //{
    //    var sohokhau = {
    //        HoTen: $("#HoTen"+ id_hokhau).val(),
    //        QuocTich: $("#QuocTich" + id_hokhau).val(),
    //        Tuoi: $("#Tuoi" + id_hokhau).val(),
    //        DiaChi: $("#DiaChi" + id_hokhau).val(),
    //        NgheNghiep: $("#NgheNghiep" + id_hokhau).val(),
    //        QuanHe: $("#QuanHe" + id_hokhau).val()
    //    };
    //};
</script>

QuanLyHocSinhDuHoc/Views/SoHoKhau/Sua.cshtml
@model QuanLyHocSinhDuHoc.Models.Entities.HoKhau

@{
    ViewBag.Title = "Sua";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Thêm mới sô hộ khẩu</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" method="post">
                        <div class="row">
                            <div class="col-md-10 col-sm-10 col-xs-10">
                                <br /><br />
                                <div class="item form-group" hidden>
                                    <input class="form-control col-md-7 col-xs-12" id="id_hokhau" name="id_hokhau"  value="@Model.id_hokhau" type="text" />
                                 </div>
                                <div class="item form-group" hidden>
                                    <input class="form-control col-md-7 col-xs-12" id="id_hs" name="id_hs"  value="@Model.id_hs" type="text" />
                                </div>
                                    <div class="item form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                            Họ tên <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input class="form-control col-md-7 col-xs-12" id="HoTen" name="HoTen" required="required" value="@Model.HoTen" type="text" />
                                        </div>
                                    </div>
                                    <div class="item form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                            Quốc tịch
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input class="form-control col-md-7 col-xs-12" id="QuocTich" name="QuocTich" type="text" value="@Model.QuocTich" />

                                        </div>
                                    </div>
                                    <div class="item form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                            Tuổi
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input class="form-control col-md-7 col-xs-12" id="Tuoi" name="Tuoi" value="@Model.Tuoi" type="number" />
                                        </div>
                                    </div>
                                    <div class="item form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                            Địa chỉ
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input class="form-control col-md-7 col-xs-12" id="DiaChi" name="DiaChi" value="@Model.DiaChi" type="text" />
                                        </div>
                                    </div>
                                    <div class="item form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                            Nghề nghiệp
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input class="form-control col-md-7 col-xs-12" id="NgheNghiep" name="NgheNghiep" value="@Model.NgheNghiep" type="text" />
                                        </div>
                                    </div>
                                    <div class="item form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                            Quan hệ
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input class="form-control col-md-7 col-xs-12" id="QuanHe" name="QuanHe" value="@Model.QuanHe" type="text" />
                                        </div>
                                    </div>
                                    <p id="messThemHS" style="color:red;font-weight:bold;"></p>
                                </div>
                        </div>

                        <div class="row">
                            <div class="ln_solid"></div>
                            @*chức năng*@
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button class="btn btn-success" type="submit" id="CapNhatSoHoKhau" style="margin-left:10%;">Lưu thông tin</button>
                                    <a href="/HocSinh/DetailChung/@Model.id_hs" class="btn btn-primary">Huỷ</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#CapNhatSoHoKhau").click(function () {
        if($("#Tuoi").val()=="" || $("#Tuoi").val()<=0)
        {
            alert("Nhập lại tuổi!!!");
            return false;
        }
        if($("#HoTen").val()=="" ||$("#QuocTich").val()==""|| $("#DiaChi").val()==""|| $("#NgheNghiep").val()==""||$("#QuanHe").val()=="" )
        {
            alert("Các giá trị khôn được để trống !!!");
            return false;
        }
    });
</script>

QuanLyHocSinhDuHoc/Views/SoHoKhau/Themmoi.cshtml
@{
    ViewBag.Title = "Themmoi";
    Layout = "~/Views/Share/_LayoutTrangChu.cshtml";
}
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Thêm mới sô hộ khẩu</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal form-label-left" method="post">
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class=" item form-group">
                                    <button  type="button" onclick="$('#fileSHK').click()" class="btn btn-sm btn-primary" style="width:230px;">Chọn file<br /><i>(Chú ý file dạng Pdf!)</i></button>
                                    <input type="file" id="fileSHK" name="fileSHK" style="display: none;" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row">                           
                            <div class="col-md-10 col-sm-10 col-xs-10">
                                <br /><br />
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Họ tên <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="HoTen" name="HoTen" required="required" placeholder="Họ tên..." type="text" />
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Quốc tịch
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="QuocTich" name="QuocTich" type="text" placeholder="Quốc tịch..." />

                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Tuổi
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="Tuoi" name="Tuoi" placeholder="Tuổi..." type="number" />
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Địa chỉ
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="DiaChi" name="DiaChi" placeholder="Địa chỉ..." type="text" />
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Nghề nghiệp
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="NgheNghiep" name="NgheNghiep" placeholder="Nghề nghiệp..." type="text" />
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Quan hệ
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input class="form-control col-md-7 col-xs-12" id="QuanHe" name="QuanHe" placeholder="Quan hệ..." type="text" />
                                    </div>
                                </div>
                                <p id="messThemHS" style="color:red;font-weight:bold;"></p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="ln_solid"></div>
                            @*chức năng*@
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button class="btn btn-success" type="submit" id="ThemmoiSoHoKhau" style="margin-left:30%;">Thêm mới</button>
                                    <a href="/HocSinh/DetailChung/@Session["id_hsSHK"]" class="btn btn-primary">Huỷ</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#ThemmoiSoHoKhau").click(function () {
        if($("#Tuoi").val()=="" || $("#Tuoi").val()<=0)
        {
            alert("Nhập lại tuổi!!!");
            return false;
        }
        if($("#HoTen").val()=="" ||$("#QuocTich").val()==""|| $("#DiaChi").val()==""|| $("#NgheNghiep").val()==""||$("#QuanHe").val()=="" )
        {
            alert("Các giá trị khôn được để trống !!!");
            return false;
        }
    });
    $(document).ready(function () {
        $("#fileSHK").change(function () {
            debugger;
            var data = new FormData();
            var files = $("#fileSHK").get(0).files;
            if (files.length > 0) {
                data.append("HelpSectionFile", files[0]);
            }
            $.ajax({
                url: "/XulyHocSinh/UpLoadFile",
                type: "POST",
                processData: false,
                contentType: false,
                data: data,
                success: function (data) {
                    if (data == "NO")
                        alert("Lỗi loại file lưu trữ");
                },
                error: function (er) {
                    alert(er);
                }

            });
        });
    });
</script>